### PR TITLE
Update node dependencies

### PR DESCRIPTION
**Pull request by Gnuk**

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
there are still some vulnerabilities which need to be fixed

**Comment by pascalgrimaud** [comment]
About upgrading automatically dependencies, we can use https://github.com/marketplace/dependabot-preview
What do you think ?

**Comment by nonomoho** [comment]
I think it could be a good idea but here the problem is more difficult. 
We discuss about it yesterday with @Gnuk and we will remove pug-cli library.

If someone add dependabot, can you ping me, I'm interested 😉

**Comment by pascalgrimaud** [comment]
> If someone add dependabot, can you ping me, I'm interested wink

I'm waiting @Gnuk's answer as he's the lead of the project. Anyway, there is nothing to do:
- go to https://github.com/marketplace/dependabot-preview
- install it to the appropriate project

That's all. It will upgrade automatically the dependencies.

**Comment by Gnuk** [comment]
Yep @pascalgrimaud Maybe we can add something like that later because currently I have two dependencies depending on outdated vulnerable package since yesterday and I'm waiting it's fixed but in // I want to not depend to pug-cli for example because we have already something processing all files that are not pug or sass for example.

Maybe I need to rework to not have those dependencies from tikui core.

**Pull request merged**
