### PR TITLE
Use tikui core and remove tech directory

### LINKED ISSUE #7: Set up test framework
Add jest and unit tests on the rendering functions.

May have conflicts with #10.

### LINKED ISSUE #9: Review tikui technical choices
Need @tikui/developers suggestions.

### LINKED ISSUE #10: Migrate tikui to a node library
Move all `tech` directory to a node independent library (something like `tikui-cli-service`).

Inspiration: @vue/cli principles.

Need @tikui/developers to have more ideas.

### PR DESCRIPTION
**Pull request by Gnuk**
Closes #10, closes #7, closes #9

Merge status:

* [x] ~Terms to use (#9)~
* [x] Build / serve
  * [x] Windows
    * [x] Show documentation CSS in `serve` mode
  * [x] Mac OS
  * [x] GNU/Linux
* [x] Core 1.x released and version updated in `package.json`

I need some review on windows and mac OS of the usage of [Tikui core](https://github.com/tikui/tikui-core)

I also need a review of Tikui-core before the draft is finished in order to release a first version.

I think we may release the first version without #18 because we can fix it later and without #6 because we need a first version to achieve it.

Please also review #9 using tikui-core to know if `componentDoc` and `templateDoc` are the best terms to use or if we will find another one.

What do you think @tikui/developers ?

### CODE REVIEW

**Comment by jeremietisserand** [comment]
@Gnuk, 
It works for with tikui-core me on linux, maybe I can try on windows but I have to setup my environment.

I just wonder how to launch tests on tikui-core project.

**Comment by Gnuk** [comment]
> I just wonder how to launch tests on tikui-core project.

Yes I saw it, I have fixed it and force push a version with tests script from npm (I used it from my IDE sorry ^^")

**Comment by pascalgrimaud** [comment]
@jeremietisserand : as you're the only one who still uses Windows, can you help the project to check the item related to `Windows` plz?

**Comment by Gnuk** [comment]
As tested on @jeremietisserand PC, there is a problem with sass serve mode for Windows, I'll try to know why. The problem is also in the current version of Tikui.

**Comment by Gnuk** [comment]
Hum I found it in Tikui Core, now it's OK for Windows :)

**Comment by Gnuk** [comment]
Hey, if you think it's OK, I will release the version `1.0.0` of Tikui Core and we will start semantic versionning :)

**Pull request merged**
