### PR TITLE
Add CI

### PR DESCRIPTION
**Pull request by nonomoho**
close https://github.com/tikui/tikui/issues/5

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
Then, don't forget to add a badge in the README!
Because it's so sexy

**Comment by Gnuk** [comment]
@pascalgrimaud Isit possible using this PR ?

**Comment by pascalgrimaud** [comment]
yes of course

**Comment by Gnuk** [comment]
So @nonomoho can you add the badge and then I'll merge ;)

**Pull request merged**
